export const SSDP_SEARCH = 'SSDP_SEARCH';
export const SSDP_SEARCH_RESPONSE = 'SSDP_SEARCH_RESPONSE';

export const SSDP_NOTIFY = 'SSDP_NOTIFY';
export const SSDP_NOTIFY_RESPONSE = 'SSDP_NOTIFY_RESPONSE';
