export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const GET_SHOPPING_LIST_START = 'GET_SHOPPING_LIST_START';
export const GET_SHOPPING_LIST_SUCCESS = 'GET_SHOPPING_LIST_SUCCESS';
export const GET_SHOPPING_LIST_FAIL = 'GET_SHOPPING_LIST_FAIL';
