export const GET_CARDS_FOR_BOARD = 'GET_CARDS_FOR_BOARD';
export const GET_CARDS_FOR_BOARD_START = 'GET_CARDS_FOR_BOARD_START';
export const GET_CARDS_FOR_BOARD_SUCCESS = 'GET_CARDS_FOR_BOARD_SUCCESS';
export const GET_CARDS_FOR_BOARD_FAIL = 'GET_CARDS_FOR_BOARD_FAIL';
