/* eslint-disable prettier/prettier */
export const SONOS_DISCOVER_DEVICES = 'SONOS_DISCOVER_DEVICES';
export const SONOS_DISCOVER_DEVICES_START = 'SONOS_DISCOVER_DEVICES_START';
export const SONOS_DISCOVER_DEVICES_FINISH = 'SONOS_DISCOVER_DEVICES_FINISH';
export const SONOS_DISCOVER_DEVICES_RESPONSE = 'SONOS_DISCOVER_DEVICES_RESPONSE';
export const SONOS_DISCOVER_DEVICES_ERROR = 'SONOS_DISCOVER_DEVICES_ERROR';

export const SONOS_PLAY_NOTIFICATION = 'SONOS_PLAY_NOTIFICATION';
export const SONOS_PLAY_NOTIFICATION_START = 'SONOS_PLAY_NOTIFICATION_START';
export const SONOS_PLAY_NOTIFICATION_SUCCESS = 'SONOS_PLAY_NOTIFICATION_SUCCESS';
export const SONOS_PLAY_NOTIFICATION_FAIL = 'SONOS_PLAY_NOTIFICATION_FAIL';

export const SONOS_GET_CURRENT_TRACK = 'SONOS_GET_CURRENT_TRACK';
export const SONOS_GET_CURRENT_TRACK_START = 'SONOS_GET_CURRENT_TRACK_START';
export const SONOS_GET_CURRENT_TRACK_SUCCESS = 'SONOS_GET_CURRENT_TRACK_SUCCESS';
export const SONOS_GET_CURRENT_TRACK_FAIL = 'SONOS_GET_CURRENT_TRACK_FAIL';

export const SONOS_CURRENT_TRACK = 'SONOS_CURRENT_TRACK';
